on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: |
        xvfb-run -a npm test
